[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32U5G9ZJTxQ with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32U545RETx"

[build]
target = "thumbv8m.main-none-eabihf"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]


[env]
DEFMT_LOG = "trace"
